{ inputs, pkgs, username, ... }: {
  imports = [
    inputs.nixos-hardware.nixosModules.common-pc-laptop
    inputs.nixos-hardware.nixosModules.common-pc-laptop-acpi_call
    inputs.nixos-hardware.nixosModules.common-pc-laptop-ssd
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-amd

    ./hardware-configuration.nix

    ../../modules/nixos/core/desktop.nix
    ../../modules/nixos/hyprland.nix

    # ../../modules/nixos/nvidia.nix
  ];

  users = {
    mutableUsers = false;
    users = {
      ${username} = {
        isNormalUser = true;
        # The hashed password with salt is generated by run `mkpasswd`.
        hashedPassword = "$y$j9T$aCiOuQh2oep9vjKMCzibC.$PbzxmaMNsarVPBDq/NY1BHzMJWUmYm1uIe.TdfnQSL.";
        home = "/home/${username}";
        extraGroups = [
          "wheel"
          "docker"
          "networkmanager"
          "audio"
          "video"
        ];
      };
    };
  };

  nix.settings.trusted-users = [ username ];

  security = {
    sudo.wheelNeedsPassword = false;
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.05"; # Did you read the comment?
}
